name: Build Plugin

on:
  push:
    paths:
      - 'sermon-filter-plugin/**'
  pull_request:
    paths:
      - 'sermon-filter-plugin/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Specify the PHP version you want to use

    - name: Zip Plugin Files
      run: |
        cd sermon-filter-plugin
        zip -r ../sermon-filter-plugin.zip . -x '*.git*' -x 'node_modules/**' -x 'vendor/**'

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sermon-filter-plugin
        path: sermon-filter-plugin.zip
